dist: xenial
language: python
python:
  - 2.7
  - 3.5
  - 3.6
  - pypy
matrix:
  include:
    - python: 3.7
      env:
        - TOX_ENV=py37
install:
  - pip install -r requirements/testing.txt
  - pip install coveralls
script:
  coverage run --source=autoslug run_tests.py
after_success:
  coveralls
notifications:
  email:
    - entrop+travis@gmail.com
